version: "3.2"

services:
  backend:
    build: ./src
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5000:5000
    depends_on:
      - postgres
  postgres:
    image: postgres:13.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=reserve-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
