"""Initial migration.

Revision ID: 0e6439be42a3
Revises: 
Create Date: 2021-05-09 11:59:28.271181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6439be42a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_product_park',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parkedByUser', sa.String(length=36), nullable=True),
    sa.Column('dateParked', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('parking_spot_id', sa.Integer(), nullable=True),
    sa.Column('parking_zone_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_product_rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rentedByUser', sa.String(length=36), nullable=True),
    sa.Column('dateRented', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_product_rent')
    op.drop_table('transfer_product_park')
    # ### end Alembic commands ###
