swagger: '2.0'

info:
  title: Reserve API
  version: "0.1"
  description: Reserve microservice
consumes:
  - application/json
produces:
  - application/json
basePath: "/api/reserves"
securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
    x-authentication-scheme: Bearer
    x-bearerInfoFunc: app.decode_token
paths:
  /:
    get:
      operationId: app.index
      summary: Health Endpoint
      responses:
        200:
          description: Return Health Status
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /transfer-products:
    get:
      security:
        - jwt: [ 'secret' ]
      tags: 
        - Reserve
      operationId: app.getAllTransferProducts
      summary: Returns all transfer products, including Rented and Parked
      responses:
        200:
          description: All Transfer Products Response
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /transfer-products/rent:
    post:
      security:
        - jwt: [ 'secret' ]
      tags: 
        - Reserve
      operationId: app.rentTransferProduct
      summary: Rent a Product
      parameters:
        - in: body
          name: request_body
          schema:
            type: object
            required:
              - product_id
            properties:
              product_id:
                type: string
      responses:
        200:
          description: Rent a Product Response
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /transfer-products/rent/pay:
    post:
      security:
        - jwt: [ 'secret' ]
      tags: 
        - Reserve
      operationId: app.payTransferProductRent
      summary: Pay for a Rented Product
      parameters:
        - in: body
          name: request_body
          schema:
            type: object
            required:
              - transfer_product_rent_id
            properties:
              transfer_product_rent_id:
                type: string
      responses:
        200:
          description: Pay Rented Product Response
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /transfer-products/park:
    post:
      security:
        - jwt: [ 'secret' ]
      tags: 
        - Reserve
      operationId: app.parkTransferProduct
      summary: Park a Product
      parameters:
        - in: body
          name: request_body
          schema:
            type: object
            required:
              - product_id
              - parking_spot_id
              - parking_zone_id
            properties:
              product_id:
                type: string
              parking_spot_id:
                type: string
              parking_zone_id:
                type: string
      responses:
        200:
          description: Park Product Response
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /transfer-products/park/pay:
    post:
      security:
        - jwt: [ 'secret' ]
      tags: 
        - Reserve
      operationId: app.payTransferProductPark
      summary: Pay for a Parked Product
      parameters:
        - in: body
          name: request_body
          schema:
            type: object
            required:
              - transfer_product_park_id
            properties:
              transfer_product_park_id:
                type: string
      responses:
        200:
          description: Pay Parked Product Response
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found