swagger: '2.0'

info:
  title: Reserve API
  version: "0.1"
  description: Reserve microservice
consumes:
  - application/json
produces:
  - application/json
basePath: "/api/reserves"
paths:
  /products:
    get:
      tags: 
        - Reserve
      operationId: app.getAllTransferProducts
      summary: Healthz endpoint
      responses:
        200:
          description: Return Health Status
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /products/rent:
    post:
      tags: 
        - Reserve
      operationId: app.rentTransferProduct
      summary: Healthz endpoint
      responses:
        200:
          description: Return Health Status
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /products/rent/pay:
    post:
      tags: 
        - Reserve
      operationId: app.payTransferProductRent
      summary: Healthz endpoint
      responses:
        200:
          description: Return Health Status
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /products/park:
    post:
      tags: 
        - Reserve
      operationId: app.parkTransferProduct
      summary: Healthz endpoint
      responses:
        200:
          description: Return Health Status
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /products/parked/pay:
    post:
      tags: 
        - Reserve
      operationId: app.payTransferProductPark
      summary: Healthz endpoint
      responses:
        200:
          description: Return Health Status
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found